language: python
python:
  - "3.6"
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov
  - pip install pandas
  - pip install xlrd
  - pip install requests
script:
  - pytest src --cov=src
after_success:
  - codecov