language: python
python:
  - "3.6"
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov
  - pip install -r requirements.txt
script:
  - pytest src -v  --cov=src --cov-report=term-missing --setup-show
after_success:
  - codecov